[theme]

# Primary accent for interactive elements
primaryColor = '#da8824'

# Background color for the main content area
backgroundColor = '#eee6d5'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#58595b'

# Color used for almost all text
textColor = 'da8824'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = "sans serif"

